import express from "express";
import bodyParser from "body-parser";
import cors from "cors";
import mongoose from "mongoose";
import multer from "multer";
import morgan from "morgan";
import path from "path";
import helmet from "helmet";
import dotenv from "dotenv";